-- Seed test students for team functionality testing
-- Run this after init.sql and rbac.sql
-- IMPORTANT: Password hashes need to be generated using BCrypt
-- Run PasswordUtil.java to generate correct hashes for password "123456"
USE awards;

-- First, ensure we have a class for testing
INSERT INTO dict_class (dept_id, class_name, enabled, sort_no)
VALUES (1, '计算机科学与技术2023级1班', 1, 1)
ON DUPLICATE KEY UPDATE class_name=VALUES(class_name);

INSERT INTO dict_class (dept_id, class_name, enabled, sort_no)
VALUES (1, '计算机科学与技术2023级2班', 1, 2)
ON DUPLICATE KEY UPDATE class_name=VALUES(class_name);

INSERT INTO dict_class (dept_id, class_name, enabled, sort_no)
VALUES (1, '软件工程2023级1班', 1, 3)
ON DUPLICATE KEY UPDATE class_name=VALUES(class_name);

-- Insert test students
-- Password: 123456
-- BCrypt hash (generated by Spring Security BCryptPasswordEncoder):
-- $2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG

INSERT INTO sys_user (username, password_hash, real_name, user_type, dept_id, student_no, class_id, enabled)
VALUES 
-- Student 1: 张三 (队长候选人) - password: 123456
('student1', '$2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG', '张三', 'STUDENT', 1, '2023001', (SELECT id FROM dict_class WHERE class_name = '计算机科学与技术2023级1班' LIMIT 1), 1),
-- Student 2: 李四 - password: 123456
('student2', '$2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG', '李四', 'STUDENT', 1, '2023002', (SELECT id FROM dict_class WHERE class_name = '计算机科学与技术2023级1班' LIMIT 1), 1),
-- Student 3: 王五 - password: 123456
('student3', '$2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG', '王五', 'STUDENT', 1, '2023003', (SELECT id FROM dict_class WHERE class_name = '计算机科学与技术2023级1班' LIMIT 1), 1),
-- Student 4: 赵六 - password: 123456
('student4', '$2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG', '赵六', 'STUDENT', 1, '2023004', (SELECT id FROM dict_class WHERE class_name = '计算机科学与技术2023级2班' LIMIT 1), 1),
-- Student 5: 钱七 - password: 123456
('student5', '$2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG', '钱七', 'STUDENT', 1, '2023005', (SELECT id FROM dict_class WHERE class_name = '计算机科学与技术2023级2班' LIMIT 1), 1),
-- Student 6: 孙八 - password: 123456
('student6', '$2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG', '孙八', 'STUDENT', 1, '2023006', (SELECT id FROM dict_class WHERE class_name = '软件工程2023级1班' LIMIT 1), 1),
-- Student 7: 周九 - password: 123456
('student7', '$2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG', '周九', 'STUDENT', 1, '2023007', (SELECT id FROM dict_class WHERE class_name = '软件工程2023级1班' LIMIT 1), 1),
-- Student 8: 吴十 - password: 123456
('student8', '$2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG', '吴十', 'STUDENT', 1, '2023008', (SELECT id FROM dict_class WHERE class_name = '软件工程2023级1班' LIMIT 1), 1)
ON DUPLICATE KEY UPDATE real_name=VALUES(real_name), password_hash=VALUES(password_hash);

-- Note: CAPTAIN role is removed - team captain is determined by biz_team.captain_id, not a global role
-- All students can create teams and become captains of their own teams

-- Assign TEACHER role to teachers
INSERT INTO sys_user (username, password_hash, real_name, user_type, dept_id, teacher_no, enabled)
VALUES 
('teacher1', '$2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG', '李老师', 'TEACHER', 1, 'T2023001', 1),
('teacher2', '$2a$10$0gPgoZXD6GwMjIdtkd6SxOd9Abbv6e8REtHuyttVk6wPHunyS.GWG', '王老师', 'TEACHER', 1, 'T2023002', 1)
ON DUPLICATE KEY UPDATE real_name=VALUES(real_name), password_hash=VALUES(password_hash);

-- Assign TEACHER role to teachers
INSERT INTO sys_user_role (user_id, role_id)
SELECT u.id, r.id FROM sys_user u, sys_role r 
WHERE u.username IN ('teacher1', 'teacher2') AND r.role_code = 'TEACHER'
ON DUPLICATE KEY UPDATE user_id=VALUES(user_id);

-- Verify the seed data
SELECT '=== Students ===' AS info;
SELECT u.id, u.username, u.real_name, u.student_no, c.class_name 
FROM sys_user u 
LEFT JOIN dict_class c ON u.class_id = c.id 
WHERE u.user_type = 'STUDENT';

SELECT '=== Teachers ===' AS info;
SELECT id, username, real_name, teacher_no FROM sys_user WHERE user_type = 'TEACHER';

SELECT '=== User Roles ===' AS info;
SELECT u.username, r.role_name 
FROM sys_user u 
JOIN sys_user_role ur ON u.id = ur.user_id 
JOIN sys_role r ON ur.role_id = r.id;
